output: ["stdout"]
file_path: ""
max_size: 100
max_backups: 30
max_age: 7
compress: true
rotation_time: "00:00"
enable_sql_log: false
sensitive_fields:
  - password
  - id_card
  - withdraw_account
  - device_id
